"""Initial migration, create user table

Revision ID: 2600af92fe14
Revises: 
Create Date: 2025-07-09 11:05:58.322894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2600af92fe14'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hashed', sa.String(length=128), nullable=False),
    sa.Column('desc', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_table_desc'), 'user_table', ['desc'], unique=False)
    op.create_index(op.f('ix_user_table_id'), 'user_table', ['id'], unique=False)
    op.create_index(op.f('ix_user_table_username'), 'user_table', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_table_username'), table_name='user_table')
    op.drop_index(op.f('ix_user_table_id'), table_name='user_table')
    op.drop_index(op.f('ix_user_table_desc'), table_name='user_table')
    op.drop_table('user_table')
    # ### end Alembic commands ###
